url: "https://yeetfolio.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Yeet's portfolio" # the name of your site, e.g. ACME Corp.
layouts_dir: "_layouts"
source: "src"
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass

